/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : ProxyData.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _ProxyData_H
#define _ProxyData_H

#ifdef __cplusplus
  extern "C" {
#endif

#define MAX_REPEATED_LENGTH 100
#define MAX_STRING_LENGTH 32

/*******************************************************************
 * General functions
 *******************************************************************/

/*
 * returns the size of a length delimited message which also 
 * contains the first bytes for the length encoding.
 */
unsigned long Message_get_delimited_size(void *_buffer, int offset);

/*
 * Tests whether a message can be completely read from the given buffer at
 * the offset. The bytes [offset..offset+length-1] are interpreted.
 *
 * Returns 1 (true) if buffer[offset..offset+length-1] contains a complete
 * message or 0 (false) otherwise.
 */
int Message_can_read_delimited_from(void *_buffer, int offset, unsigned int length);



/*******************************************************************
 * Message: ProxyData.proto, line 13
 *******************************************************************/

/* Maximum size of a serialized ServoEscPacket-message, useful for buffer allocation. */
#define MAX_ServoEscPacket_SIZE 26

/* Structure that holds a deserialized ServoEscPacket-message. */
struct ServoEscPacket {
    signed long _servo;
    signed long _motor;
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int ServoEscPacket_write_delimited_to(struct ServoEscPacket *_ServoEscPacket, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int ServoEscPacket_write_with_tag(struct ServoEscPacket *_ServoEscPacket, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int ServoEscPacket_read_delimited_from(void *_buffer, struct ServoEscPacket *_ServoEscPacket, int offset);


/*******************************************************************
 * Message: ProxyData.proto, line 7
 *******************************************************************/

/* Maximum size of a serialized IrUsPacket-message, useful for buffer allocation. */
#define MAX_IrUsPacket_SIZE 38

/* Structure that holds a deserialized IrUsPacket-message. */
struct IrUsPacket {
    signed long _ir1;
    signed long _us1;
    signed long _us2;
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int IrUsPacket_write_delimited_to(struct IrUsPacket *_IrUsPacket, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int IrUsPacket_write_with_tag(struct IrUsPacket *_IrUsPacket, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int IrUsPacket_read_delimited_from(void *_buffer, struct IrUsPacket *_IrUsPacket, int offset);



#ifdef __cplusplus
  }
#endif

#endif
